<a href="https://colab.research.google.com/github/kanksha14/FSM-Assignment/blob/main/Bearing_DataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [ ]:
#install Kaggle
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"akank14","key":"ecc9ce2a5d2cf1efd46a4334002298d1"}'}

In [ ]:
#create a kaggle folder
! mkdir ~/.kaggle

In [ ]:
#copy the kaggle.json to folder created
! cp kaggle.json  ~/.kaggle

In [ ]:
#Permission for the json to act
! chmod 600  ~/.kaggle

In [ ]:
# 1. GTSRB - German Traffic Sign Recognition Benchmark
!kaggle datasets download -d vinayak123tyagi/bearing-dataset

 99% 1.55G/1.56G [00:12<00:00, 141MB/s]
100% 1.56G/1.56G [00:12<00:00, 136MB/s]


In [ ]:
!unzip bearing-dataset.zip

Streaming output truncated to the last 5000 lines.
  inflating: 3rd_test/4th_test/txt/2004.03.13.14.12.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.14.22.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.14.32.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.14.42.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.14.52.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.02.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.12.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.22.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.32.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.42.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.15.52.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.16.02.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.16.12.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.16.22.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.16.32.46  
  inflating: 3rd_test/4th_test/txt/2004.03.13.16.42.46  
  inflating: 3rd_test/4th_test/txt/20

In [ ]:
import matplotlib.pyplot as plt
import scipy.io
import numpy as np
import pandas as pd
import os

In [ ]:
path1 ='/content/1st_test/1st_test'
path2 ='/content/2nd_test/2nd_test'
path3 ='/content/3rd_test/4th_test/txt'

#names = col_names2
col_names1 = ['Bearing 1 – Ch 1','Bearing 1 – Ch 2', 'Bearing 2 – Ch 3','Bearing 2 – Ch 4', 'Bearing 3 – Ch 5','Bearing 3 – Ch 6', 'Bearing 4 – Ch 7','Bearing 4 – Ch 8']
col_names2 = ['Bearing 1 – Ch 1', 'Bearing 2 – Ch 2','Bearing 3 – Ch 3', 'Bearing 4 – Ch 4']
col_names3 = ['Bearing 1 – Ch 1', 'Bearing 2 – Ch 2','Bearing 3 – Ch 3', 'Bearing 4 – Ch 4']



In [ ]:
#Files cont inside each folder

initial_count = 0
for path in os.listdir(path1):
    if os.path.isfile(os.path.join(path1, path)):
        initial_count += 1
print("Test set 1 : ",initial_count)
print("---------------------------------\n")

initial_count = 0
for path in os.listdir(path2):
    if os.path.isfile(os.path.join(path2, path)):
        initial_count += 1
print("Test set 2 : ",initial_count)
print("---------------------------------\n")

initial_count = 0
for path in os.listdir(path3):
    if os.path.isfile(os.path.join(path3, path)):
        initial_count += 1
print("Test set 3 : ",initial_count)
print("---------------------------------\n")

Test set 1 :  2156
---------------------------------

Test set 2 :  984
---------------------------------

Test set 3 :  6324
---------------------------------



In [ ]:
filename1 = '2003.10.22.12.06.24'
df_test1 = pd.read_csv(os.path.join(path1,filename1), names = col_names1, sep='\t')
print(df_test1.head(),"\n")
print("---------------------------------\n")

filename2 = '2004.02.12.10.32.39'
df_test2 = pd.read_csv(os.path.join(path2,filename2),sep='\t',names = col_names2)
print(df_test2.head(),"\n")
print("---------------------------------\n")

filename3 = '2004.03.04.09.27.46'
df_test3 = pd.read_csv(os.path.join(path3,filename3), names = col_names3, sep='\t')
print(df_test3.head())
print("---------------------------------\n")

   Bearing 1 – Ch 1  Bearing 1 – Ch 2  Bearing 2 – Ch 3  Bearing 2 – Ch 4  \
0            -0.022            -0.039            -0.183            -0.054   
1            -0.105            -0.017            -0.164            -0.183   
2            -0.183            -0.098            -0.195            -0.125   
3            -0.178            -0.161            -0.159            -0.178   
4            -0.208            -0.129            -0.261            -0.098   

   Bearing 3 – Ch 5  Bearing 3 – Ch 6  Bearing 4 – Ch 7  Bearing 4 – Ch 8  
0            -0.105            -0.134            -0.129            -0.142  
1            -0.049             0.029            -0.115            -0.122  
2            -0.005            -0.007            -0.171            -0.071  
3            -0.100            -0.115            -0.112            -0.078  
4            -0.151            -0.205            -0.063            -0.066   

---------------------------------

   Bearing 1 – Ch 1  Bearing 2 – Ch 2  Beari

In [ ]:
#converting column1 into array of df_test1
bearing_no = 1
bearing_data = np.array(df_test1.iloc[:,1])
temp = bearing_data
temp

array([-0.039, -0.017, -0.098, ..., -0.303,  0.076,  0.098])

In [ ]:
len(temp)

20480

In [ ]:
#extracting features from this bearing data

feature_matrix = np.zeros((1,9))
feature_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Calculating time domain features:



*  Maximum Value
*  Minimum Value
*  Mean Value
*  Standard Value (Unbiased std)
*  Root mean square value (RMS)
*  Skewness
*  Kurtosis
*  Crest factor = Max/RMS
*  Form factor = RMS/Mean



In [ ]:
def compute_skewness(x):
  n = len(x)
  third_moment = np.sum((x - np.mean(x))**3)/n
  s_3 = np.std(x, ddof = 1) ** 3
  return third_moment/s_3

def compute_kurtosis(x):
  n = len(x)
  fourth_moment = np.sum((x - np.mean(x))**4)/n
  s_4 = np.std(x, ddof = 1) ** 4
  return fourth_moment / s_4 - 3

In [ ]:
#calculating time domain features for df_test1 files
feature_matrix[0,0] = np.max(temp)
feature_matrix[0,1] = np.min(temp)
feature_matrix[0,2] = np.mean(temp)
feature_matrix[0,3] = np.std(temp, ddof = 1)
feature_matrix[0,4] = np.sqrt(np.mean(temp**2))
feature_matrix[0,5] = compute_skewness(temp)
feature_matrix[0,6] = compute_kurtosis(temp)
feature_matrix[0,7] = feature_matrix[0,0]/feature_matrix[0,4]
feature_matrix[0,8] = feature_matrix[0,4]/feature_matrix[0,2]

In [ ]:
feature_matrix

array([[ 0.701     , -0.564     , -0.09388013,  0.07064989,  0.11749315,
         0.22009984,  3.06529124,  5.9663051 , -1.25152316]])

In [ ]:
filename1

'2003.10.22.12.06.24'

In [ ]:
df = pd.DataFrame(feature_matrix)
df.index = [filename1]
df


0      1        2        3         4       5  \
2003.10.22.12.06.24  0.701 -0.564 -0.09388  0.07065  0.117493  0.2201   

                            6         7         8  
2003.10.22.12.06.24  3.065291  5.966305 -1.251523

In [ ]:
time_feature_matrix = pd.DataFrame()

bearing_no = 1
for filename in os.listdir(path1):
  dataset = pd.read_csv(os.path.join(path1, filename), sep='\t',header=None)
  bearing_data = np.array(dataset.iloc[:,bearing_no-1])

  feature_matrix = np.zeros((1,9))
  temp = bearing_data

  feature_matrix[0,0] = np.max(temp)
  feature_matrix[0,1] = np.min(temp)
  feature_matrix[0,2] = np.mean(temp)
  feature_matrix[0,3] = np.std(temp, ddof = 1)
  feature_matrix[0,4] = np.sqrt(np.mean(temp**2))
  feature_matrix[0,5] = compute_skewness(temp)
  feature_matrix[0,6] = compute_kurtosis(temp)
  feature_matrix[0,7] = feature_matrix[0,0]/feature_matrix[0,4]
  feature_matrix[0,8] = feature_matrix[0,4]/feature_matrix[0,2]
  #print(filename)
  df = pd.DataFrame(feature_matrix)
  df.index = [filename]

  time_feature_matrix = time_feature_matrix.append(df)

In [ ]:
time_feature_matrix

0      1         2         3         4         5  \
2003.11.16.10.48.46  0.615 -0.757 -0.117362  0.099195  0.153665 -0.018518   
2003.11.23.03.36.56  0.454 -0.659 -0.116812  0.101355  0.154652 -0.013852   
2003.11.14.19.48.46  0.598 -0.806 -0.117707  0.100533  0.154795 -0.015871   
2003.10.31.15.11.44  0.369 -0.669 -0.117602  0.092586  0.149673 -0.036802   
2003.10.31.07.49.46  0.486 -0.693 -0.117018  0.094730  0.150554 -0.058077   
...                    ...    ...       ...       ...       ...       ...   
2003.10.31.20.01.44  0.479 -0.764 -0.117309  0.092074  0.149126 -0.037031   
2003.11.01.21.51.44  0.466 -0.667 -0.118129  0.095201  0.151715 -0.066715   
2003.11.09.00.01.44  0.557 -0.835 -0.117054  0.099099  0.153368 -0.070772   
2003.10.31.02.09.46  0.464 -0.659 -0.115197  0.094456  0.148969 -0.061756   
2003.11.22.03.26.56  0.364 -0.830 -0.118905  0.101519  0.156346 -0.090973   

                            6         7         8  
2003.11.16.10.48.46  1.202036  4.002206 -1.309326  
2003.11.23.03.36.56  1.051685  2.935615 -1.323944  
2003.11.14.19.48.46  1.436166  3.863179 -1.315081  
2003.10.31.15.11.44  0.969644  2.465370 -1.272706  
2003.10.31.07.49.46  1.185588  3.228080 -1.286588  
...                       ...       ...       ...  
2003.10.31.20.01.44  1.090762  3.212044 -1.271225  
2003.11.01.21.51.44  0.939835  3.071554 -1.284310  
2003.11.09.00.01.44  1.252520  3.631781 -1.310230  
2003.10.31.02.09.46  0.912389  3.114738 -1.293168  
2003.11.22.03.26.56  0.943109  2.328172 -1.314876  

[2156 rows x 9 columns]

In [ ]:
time_feature_matrix.columns = ['Maximum Value','Minimum Value','Mean Value','Standard Value','Root mean square value','Skewness','Kurtosis','Crest factor','Form factor']
time_feature_matrix.columns = pd.to_datetime(time_feature_matrix.index, format='%Y.%m.%d.%H.%M.%S')

time_feature_matrix = time_feature_matrix.sort_index()
time_feature_matrix


ValueError: ignored

In [ ]:
pd.to_datetime(time_feature_matrix.index)

ParserError: ignored